# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49cbae5f8bcd945f05c0dff9c0666049514624457b829c9104713ae570598cf19268a8545a2a6e3f65cf5800e41c63b51c4d0411ae5e23aeaa9487168a8cf932

test:
  secret_key_base: 93f7b8bce10a1fffb86dbf3801be6d11ba596c878ead68fd30af44ca4f6e494c14fa7fe0fd21e6de8514687f6debac307dec115dbadc2d7dfbdeadb43375adba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
